///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GuestLoginResqonse {
/*
{
  "guestToken": "f092182aced14afeb8ac3a577dac69b51720607088332",
  "responseCode": "0",
  "responseDesc": "Process service request successfully.",
  "serverTimestamp": 1720607088334,
  "isReCheckFlag": "0"
} 
*/

  String? guestToken;
  String? responseCode;
  String? responseDesc;
  int? serverTimestamp;
  String? isReCheckFlag;

  GuestLoginResqonse({
    this.guestToken,
    this.responseCode,
    this.responseDesc,
    this.serverTimestamp,
    this.isReCheckFlag,
  });

  GuestLoginResqonse.fromJson(Map<String, dynamic> json) {
    guestToken = json['guestToken']?.toString();
    responseCode = json['responseCode']?.toString();
    responseDesc = json['responseDesc']?.toString();
    serverTimestamp = json['serverTimestamp']?.toInt();
    isReCheckFlag = json['isReCheckFlag']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['guestToken'] = guestToken;
    data['responseCode'] = responseCode;
    data['responseDesc'] = responseDesc;
    data['serverTimestamp'] = serverTimestamp;
    data['isReCheckFlag'] = isReCheckFlag;
    return data;
  }
}
