///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewTransRecordListResqonseTransRecordList implements Comparable {
/*
{
  "orderId": "01003471040597428664",
  "logo": "icon_history_transfer",
  "iosLogo": "icon_history_transfer",
  "tradeType": "从充值 ******6698",
  "tradeTime": 1719960924000,
  "amount": 145,
  "oppositeName": "DAW HTWE HTWE",
  "currency": "Ks",
  "totalAmount": 145,
  "debitOrCredit": "C",
  "historyTitle": "从充值 DAW HTWE HTWE"
} 
*/

  String? orderId;
  String? logo;
  String? iosLogo;
  String? tradeType;
  int? tradeTime;
  int? amount;
  String? oppositeName;
  String? currency;
  int? totalAmount;
  String? debitOrCredit;
  String? historyTitle;

  NewTransRecordListResqonseTransRecordList({
    this.orderId,
    this.logo,
    this.iosLogo,
    this.tradeType,
    this.tradeTime,
    this.amount,
    this.oppositeName,
    this.currency,
    this.totalAmount,
    this.debitOrCredit,
    this.historyTitle,
  });
  NewTransRecordListResqonseTransRecordList.fromJson(
      Map<String, dynamic> json) {
    orderId = json['orderId']?.toString();
    logo = json['logo']?.toString();
    iosLogo = json['iosLogo']?.toString();
    tradeType = json['tradeType']?.toString();
    tradeTime = json['tradeTime']?.toInt();
    amount = json['amount']?.toInt();
    oppositeName = json['oppositeName']?.toString();
    currency = json['currency']?.toString();
    totalAmount = json['totalAmount']?.toInt();
    debitOrCredit = json['debitOrCredit']?.toString();
    historyTitle = json['historyTitle']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['orderId'] = orderId;
    data['logo'] = logo;
    data['iosLogo'] = iosLogo;
    data['tradeType'] = tradeType;
    data['tradeTime'] = tradeTime;
    data['amount'] = amount;
    data['oppositeName'] = oppositeName;
    data['currency'] = currency;
    data['totalAmount'] = totalAmount;
    data['debitOrCredit'] = debitOrCredit;
    data['historyTitle'] = historyTitle;
    return data;
  }

  @override
  int compareTo(other) {
    if (other is NewTransRecordListResqonseTransRecordList) {
      if (tradeTime == other.tradeTime) return 0;
      return tradeTime! - other.tradeTime!;
    }
    return 0;
  }
}

class NewTransRecordListResqonse {
/*
{
  "transRecordList": [
    {
      "orderId": "01003471040597428664",
      "logo": "icon_history_transfer",
      "iosLogo": "icon_history_transfer",
      "tradeType": "从充值 ******6698",
      "tradeTime": 1719960924000,
      "tradeTime": 1720780372740,
      "amount": 145,
      "oppositeName": "DAW HTWE HTWE",
      "currency": "Ks",
      "totalAmount": 145,
      "debitOrCredit": "C",
      "historyTitle": "从充值 DAW HTWE HTWE"
    }
  ],
  "responseCode": "0",
  "responseDesc": "Process service request successfully.",
  "serverTimestamp": 1720775929002,
  "isReCheckFlag": "0"
} 
*/

  List<NewTransRecordListResqonseTransRecordList?>? transRecordList;
  String? responseCode;
  String? responseDesc;
  int? serverTimestamp;
  String? isReCheckFlag;

  NewTransRecordListResqonse({
    this.transRecordList,
    this.responseCode,
    this.responseDesc,
    this.serverTimestamp,
    this.isReCheckFlag,
  });
  NewTransRecordListResqonse.fromJson(Map<String, dynamic> json) {
    if (json['transRecordList'] != null) {
      final v = json['transRecordList'];
      final arr0 = <NewTransRecordListResqonseTransRecordList>[];
      v.forEach((v) {
        arr0.add(NewTransRecordListResqonseTransRecordList.fromJson(v));
      });
      transRecordList = arr0;
    }
    responseCode = json['responseCode']?.toString();
    responseDesc = json['responseDesc']?.toString();
    serverTimestamp = json['serverTimestamp']?.toInt();
    isReCheckFlag = json['isReCheckFlag']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (transRecordList != null) {
      final v = transRecordList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['transRecordList'] = arr0;
    }
    data['responseCode'] = responseCode;
    data['responseDesc'] = responseDesc;
    data['serverTimestamp'] = serverTimestamp;
    data['isReCheckFlag'] = isReCheckFlag;
    return data;
  }
}
