///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: non_constant_identifier_names
class ErrResponseResponseBodyResponseDetail {
/*
{
  "IsReCheckFlag": "0",
  "ResultDesc": "è´¦å·å·²å¨å¶ä»è®¾å¤ç»å½ï¼è¯·éæ°ç»å½ãä¸ºäºæ¨çè´¦å·å®å¨ï¼è¯·å¿å°ç­ä¿¡éªè¯ç ææ¯ä»å¯ç åäº«ç»ä»»ä½äºº",
  "ResultCode": "AS403"
} 
*/

  String? IsReCheckFlag;
  String? ResultDesc;
  String? ResultCode;

  ErrResponseResponseBodyResponseDetail({
    this.IsReCheckFlag,
    this.ResultDesc,
    this.ResultCode,
  });
  ErrResponseResponseBodyResponseDetail.fromJson(Map<String, dynamic> json) {
    IsReCheckFlag = json['IsReCheckFlag']?.toString();
    ResultDesc = json['ResultDesc']?.toString();
    ResultCode = json['ResultCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['IsReCheckFlag'] = IsReCheckFlag;
    data['ResultDesc'] = ResultDesc;
    data['ResultCode'] = ResultCode;
    return data;
  }
}

class ErrResponseResponseBody {
/*
{
  "ResponseCode": "AS403",
  "ResponseDesc": "è´¦å·å·²å¨å¶ä»è®¾å¤ç»å½ï¼è¯·éæ°ç»å½ãä¸ºäºæ¨çè´¦å·å®å¨ï¼è¯·å¿å°ç­ä¿¡éªè¯ç ææ¯ä»å¯ç åäº«ç»ä»»ä½äºº",
  "ResponseDetail": {
    "IsReCheckFlag": "0",
    "ResultDesc": "è´¦å·å·²å¨å¶ä»è®¾å¤ç»å½ï¼è¯·éæ°ç»å½ãä¸ºäºæ¨çè´¦å·å®å¨ï¼è¯·å¿å°ç­ä¿¡éªè¯ç ææ¯ä»å¯ç åäº«ç»ä»»ä½äºº",
    "ResultCode": "AS403"
  }
} 
*/

  String? ResponseCode;
  String? ResponseDesc;
  ErrResponseResponseBodyResponseDetail? ResponseDetail;

  ErrResponseResponseBody({
    this.ResponseCode,
    this.ResponseDesc,
    this.ResponseDetail,
  });
  ErrResponseResponseBody.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseDesc = json['ResponseDesc']?.toString();
    ResponseDetail = (json['ResponseDetail'] != null)
        ? ErrResponseResponseBodyResponseDetail.fromJson(json['ResponseDetail'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseDesc'] = ResponseDesc;
    if (ResponseDetail != null) {
      data['ResponseDetail'] = ResponseDetail!.toJson();
    }
    return data;
  }
}

class ErrResponseResponseHeader {
/*
{
  "Version": "",
  "ConversationID": ""
} 
*/

  String? Version;
  String? ConversationID;

  ErrResponseResponseHeader({
    this.Version,
    this.ConversationID,
  });
  ErrResponseResponseHeader.fromJson(Map<String, dynamic> json) {
    Version = json['Version']?.toString();
    ConversationID = json['ConversationID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Version'] = Version;
    data['ConversationID'] = ConversationID;
    return data;
  }
}

class ErrResponseResponse {
/*
{
  "Header": {
    "Version": "",
    "ConversationID": ""
  },
  "Body": {
    "ResponseCode": "AS403",
    "ResponseDesc": "è´¦å·å·²å¨å¶ä»è®¾å¤ç»å½ï¼è¯·éæ°ç»å½ãä¸ºäºæ¨çè´¦å·å®å¨ï¼è¯·å¿å°ç­ä¿¡éªè¯ç ææ¯ä»å¯ç åäº«ç»ä»»ä½äºº",
    "ResponseDetail": {
      "IsReCheckFlag": "0",
      "ResultDesc": "è´¦å·å·²å¨å¶ä»è®¾å¤ç»å½ï¼è¯·éæ°ç»å½ãä¸ºäºæ¨çè´¦å·å®å¨ï¼è¯·å¿å°ç­ä¿¡éªè¯ç ææ¯ä»å¯ç åäº«ç»ä»»ä½äºº",
      "ResultCode": "AS403"
    }
  }
} 
*/

  ErrResponseResponseHeader? Header;
  ErrResponseResponseBody? Body;

  ErrResponseResponse({
    this.Header,
    this.Body,
  });
  ErrResponseResponse.fromJson(Map<String, dynamic> json) {
    Header = (json['Header'] != null)
        ? ErrResponseResponseHeader.fromJson(json['Header'])
        : null;
    Body = (json['Body'] != null)
        ? ErrResponseResponseBody.fromJson(json['Body'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Header != null) {
      data['Header'] = Header!.toJson();
    }
    if (Body != null) {
      data['Body'] = Body!.toJson();
    }
    return data;
  }
}

class ErrResponse {
/*
{
  "Response": {
    "Header": {
      "Version": "",
      "ConversationID": ""
    },
    "Body": {
      "ResponseCode": "AS403",
      "ResponseDesc": "è´¦å·å·²å¨å¶ä»è®¾å¤ç»å½ï¼è¯·éæ°ç»å½ãä¸ºäºæ¨çè´¦å·å®å¨ï¼è¯·å¿å°ç­ä¿¡éªè¯ç ææ¯ä»å¯ç åäº«ç»ä»»ä½äºº",
      "ResponseDetail": {
        "IsReCheckFlag": "0",
        "ResultDesc": "è´¦å·å·²å¨å¶ä»è®¾å¤ç»å½ï¼è¯·éæ°ç»å½ãä¸ºäºæ¨çè´¦å·å®å¨ï¼è¯·å¿å°ç­ä¿¡éªè¯ç ææ¯ä»å¯ç åäº«ç»ä»»ä½äºº",
        "ResultCode": "AS403"
      }
    }
  }
} 
*/

  ErrResponseResponse? Response;

  ErrResponse({
    this.Response,
  });
  ErrResponse.fromJson(Map<String, dynamic> json) {
    Response = (json['Response'] != null)
        ? ErrResponseResponse.fromJson(json['Response'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Response != null) {
      data['Response'] = Response!.toJson();
    }
    return data;
  }
}
