///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginForSmsCodeResqonse1UserInfo {
/*
{
  "idType": "01",
  "identityId": "202000000015071976",
  "fullName": "Daw Theingi Kyaw",
  "token": "d2d37a24ddf8d3dc5e4927b59c8347931742460059413"
} 
*/

  String? idType;
  String? identityId;
  String? fullName;
  String? token;

  LoginForSmsCodeResqonse1UserInfo({
    this.idType,
    this.identityId,
    this.fullName,
    this.token,
  });
  LoginForSmsCodeResqonse1UserInfo.fromJson(Map<String, dynamic> json) {
    idType = json['idType']?.toString();
    identityId = json['identityId']?.toString();
    fullName = json['fullName']?.toString();
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idType'] = idType;
    data['identityId'] = identityId;
    data['fullName'] = fullName;
    data['token'] = token;
    return data;
  }
}

class LoginForSmsCodeResqonse1 {
/*
{
  "kycCheckFlag": "0",
  "pinCheckFlag": "0",
  "deviceCheckFlag": "1",
  "nameCheckFlag": "0",
  "faceVerifyEnable": "0",
  "nrcVerifyEnable": "1",
  "userInfo": {
    "idType": "01",
    "identityId": "202000000015071976",
    "fullName": "Daw Theingi Kyaw",
    "token": "d2d37a24ddf8d3dc5e4927b59c8347931742460059413"
  },
  "needCollectData": false,
  "responseCode": "0",
  "responseDesc": "Process service request successfully.",
  "serverTimestamp": 1742460059363,
  "isReCheckFlag": "0"
} 
*/

  String? kycCheckFlag;
  String? pinCheckFlag;
  String? deviceCheckFlag;
  String? nameCheckFlag;
  String? faceVerifyEnable;
  String? nrcVerifyEnable;
  LoginForSmsCodeResqonse1UserInfo? userInfo;
  bool? needCollectData;
  String? responseCode;
  String? responseDesc;
  int? serverTimestamp;
  String? isReCheckFlag;

  LoginForSmsCodeResqonse1({
    this.kycCheckFlag,
    this.pinCheckFlag,
    this.deviceCheckFlag,
    this.nameCheckFlag,
    this.faceVerifyEnable,
    this.nrcVerifyEnable,
    this.userInfo,
    this.needCollectData,
    this.responseCode,
    this.responseDesc,
    this.serverTimestamp,
    this.isReCheckFlag,
  });
  LoginForSmsCodeResqonse1.fromJson(Map<String, dynamic> json) {
    kycCheckFlag = json['kycCheckFlag']?.toString();
    pinCheckFlag = json['pinCheckFlag']?.toString();
    deviceCheckFlag = json['deviceCheckFlag']?.toString();
    nameCheckFlag = json['nameCheckFlag']?.toString();
    faceVerifyEnable = json['faceVerifyEnable']?.toString();
    nrcVerifyEnable = json['nrcVerifyEnable']?.toString();
    userInfo = (json['userInfo'] != null)
        ? LoginForSmsCodeResqonse1UserInfo.fromJson(json['userInfo'])
        : null;
    needCollectData = json['needCollectData'];
    responseCode = json['responseCode']?.toString();
    responseDesc = json['responseDesc']?.toString();
    serverTimestamp = json['serverTimestamp']?.toInt();
    isReCheckFlag = json['isReCheckFlag']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kycCheckFlag'] = kycCheckFlag;
    data['pinCheckFlag'] = pinCheckFlag;
    data['deviceCheckFlag'] = deviceCheckFlag;
    data['nameCheckFlag'] = nameCheckFlag;
    data['faceVerifyEnable'] = faceVerifyEnable;
    data['nrcVerifyEnable'] = nrcVerifyEnable;
    if (userInfo != null) {
      data['userInfo'] = userInfo!.toJson();
    }
    data['needCollectData'] = needCollectData;
    data['responseCode'] = responseCode;
    data['responseDesc'] = responseDesc;
    data['serverTimestamp'] = serverTimestamp;
    data['isReCheckFlag'] = isReCheckFlag;
    return data;
  }
}
