///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginForSmsCodeResqonse {
/*
{
  "businessUniqueId": "81cecc69e3ca83b490a28dec5336b210e2138923796d1bf76598704629af2418",
  "needVerify": "true",
  "verifyType": "PIN",
  "needCollectData": false,
  "responseCode": "0",
  "responseDesc": "Process service request successfully.",
  "serverTimestamp": 1742397664676,
  "isReCheckFlag": "0"
} 
*/

  String? businessUniqueId;
  String? needVerify;
  String? verifyType;
  bool? needCollectData;
  String? responseCode;
  String? responseDesc;
  int? serverTimestamp;
  String? isReCheckFlag;
  String? token;

  LoginForSmsCodeResqonse({
    this.businessUniqueId,
    this.needVerify,
    this.verifyType,
    this.needCollectData,
    this.responseCode,
    this.responseDesc,
    this.serverTimestamp,
    this.isReCheckFlag,
    this.token,
  });
  LoginForSmsCodeResqonse.fromJson(Map<String, dynamic> json) {
    businessUniqueId = json['businessUniqueId']?.toString();
    needVerify = json['needVerify']?.toString();
    verifyType = json['verifyType']?.toString();
    needCollectData = json['needCollectData'];
    responseCode = json['responseCode']?.toString();
    responseDesc = json['responseDesc']?.toString();
    serverTimestamp = json['serverTimestamp']?.toInt();
    isReCheckFlag = json['isReCheckFlag']?.toString();
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['businessUniqueId'] = businessUniqueId;
    data['needVerify'] = needVerify;
    data['verifyType'] = verifyType;
    data['needCollectData'] = needCollectData;
    data['responseCode'] = responseCode;
    data['responseDesc'] = responseDesc;
    data['serverTimestamp'] = serverTimestamp;
    data['isReCheckFlag'] = isReCheckFlag;
    data['token'] = token;
    return data;
  }
}
