///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TransferToAccountResqonseResponseBodyResponseDetail {
/*
{
  "ServerTimestamp": 1752227786716,
  "OrderNo": "01003844020672099152"
} 
*/

  int? ServerTimestamp;
  String? OrderNo;

  TransferToAccountResqonseResponseBodyResponseDetail({
    this.ServerTimestamp,
    this.OrderNo,
  });
  TransferToAccountResqonseResponseBodyResponseDetail.fromJson(Map<String, dynamic> json) {
    ServerTimestamp = json['ServerTimestamp']?.toInt();
    OrderNo = json['OrderNo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ServerTimestamp'] = ServerTimestamp;
    data['OrderNo'] = OrderNo;
    return data;
  }
}

class TransferToAccountResqonseResponseBody {
/*
{
  "ResponseCode": "0",
  "ResponseDesc": "Accept the service request successfully.",
  "ResponseDetail": {
    "ServerTimestamp": 1752227786716,
    "OrderNo": "01003844020672099152"
  }
} 
*/

  String? ResponseCode;
  String? ResponseDesc;
  TransferToAccountResqonseResponseBodyResponseDetail? ResponseDetail;

  TransferToAccountResqonseResponseBody({
    this.ResponseCode,
    this.ResponseDesc,
    this.ResponseDetail,
  });
  TransferToAccountResqonseResponseBody.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseDesc = json['ResponseDesc']?.toString();
    ResponseDetail = (json['ResponseDetail'] != null) ? TransferToAccountResqonseResponseBodyResponseDetail.fromJson(json['ResponseDetail']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseDesc'] = ResponseDesc;
    if (ResponseDetail != null) {
      data['ResponseDetail'] = ResponseDetail!.toJson();
    }
    return data;
  }
}

class TransferToAccountResqonseResponseHeader {
/*
{
  "Version": "5.8.2",
  "ConversationID": ""
} 
*/

  String? Version;
  String? ConversationID;

  TransferToAccountResqonseResponseHeader({
    this.Version,
    this.ConversationID,
  });
  TransferToAccountResqonseResponseHeader.fromJson(Map<String, dynamic> json) {
    Version = json['Version']?.toString();
    ConversationID = json['ConversationID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Version'] = Version;
    data['ConversationID'] = ConversationID;
    return data;
  }
}

class TransferToAccountResqonseResponse {
/*
{
  "Header": {
    "Version": "5.8.2",
    "ConversationID": ""
  },
  "Body": {
    "ResponseCode": "0",
    "ResponseDesc": "Accept the service request successfully.",
    "ResponseDetail": {
      "ServerTimestamp": 1752227786716,
      "OrderNo": "01003844020672099152"
    }
  }
} 
*/

  TransferToAccountResqonseResponseHeader? Header;
  TransferToAccountResqonseResponseBody? Body;

  TransferToAccountResqonseResponse({
    this.Header,
    this.Body,
  });
  TransferToAccountResqonseResponse.fromJson(Map<String, dynamic> json) {
    Header = (json['Header'] != null) ? TransferToAccountResqonseResponseHeader.fromJson(json['Header']) : null;
    Body = (json['Body'] != null) ? TransferToAccountResqonseResponseBody.fromJson(json['Body']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Header != null) {
      data['Header'] = Header!.toJson();
    }
    if (Body != null) {
      data['Body'] = Body!.toJson();
    }
    return data;
  }
}

class TransferToAccountResqonse {
/*
{
  "Response": {
    "Header": {
      "Version": "5.8.2",
      "ConversationID": ""
    },
    "Body": {
      "ResponseCode": "0",
      "ResponseDesc": "Accept the service request successfully.",
      "ResponseDetail": {
        "ServerTimestamp": 1752227786716,
        "OrderNo": "01003844020672099152"
      }
    }
  }
} 
*/

  TransferToAccountResqonseResponse? Response;

  TransferToAccountResqonse({
    this.Response,
  });
  TransferToAccountResqonse.fromJson(Map<String, dynamic> json) {
    Response = (json['Response'] != null) ? TransferToAccountResqonseResponse.fromJson(json['Response']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Response != null) {
      data['Response'] = Response!.toJson();
    }
    return data;
  }
}
