///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VerifyQrCodeResqonseQrCodes {
/*
{
  "qrCode": "KBZPayRQR01GTE5wZTRFeVVuTFpaeUpWX0dYV3Y2NHJzZDVTX1B5UWFoaXp2MUtIekNp",
  "validateTime": 1745671774150,
  "expiredTime": 1745671834150
} 
*/

  String? qrCode;
  int? validateTime;
  int? expiredTime;

  VerifyQrCodeResqonseQrCodes({
    this.qrCode,
    this.validateTime,
    this.expiredTime,
  });
  VerifyQrCodeResqonseQrCodes.fromJson(Map<String, dynamic> json) {
    qrCode = json['qrCode']?.toString();
    validateTime = json['validateTime']?.toInt();
    expiredTime = json['expiredTime']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['qrCode'] = qrCode;
    data['validateTime'] = validateTime;
    data['expiredTime'] = expiredTime;
    return data;
  }
}

class VerifyQrCodeResqonse {
/*
{
  "responseCode": "0",
  "responseDesc": "Process service request successfully.",
  "serverTimestamp": 1745671774150,
  "isReCheckFlag": "0",
  "serialNo": "ZZyJV_GXWv64rsd5S_PyQahi",
  "qrCodes": [
    {
      "qrCode": "KBZPayRQR01GTE5wZTRFeVVuTFpaeUpWX0dYV3Y2NHJzZDVTX1B5UWFoaXp2MUtIekNp",
      "validateTime": 1745671774150,
      "expiredTime": 1745671834150
    }
  ]
} 
*/

  String? responseCode;
  String? responseDesc;
  int? serverTimestamp;
  String? isReCheckFlag;
  String? serialNo;
  List<VerifyQrCodeResqonseQrCodes?>? qrCodes;

  VerifyQrCodeResqonse({
    this.responseCode,
    this.responseDesc,
    this.serverTimestamp,
    this.isReCheckFlag,
    this.serialNo,
    this.qrCodes,
  });
  VerifyQrCodeResqonse.fromJson(Map<String, dynamic> json) {
    responseCode = json['responseCode']?.toString();
    responseDesc = json['responseDesc']?.toString();
    serverTimestamp = json['serverTimestamp']?.toInt();
    isReCheckFlag = json['isReCheckFlag']?.toString();
    serialNo = json['serialNo']?.toString();
    if (json['qrCodes'] != null) {
      final v = json['qrCodes'];
      final arr0 = <VerifyQrCodeResqonseQrCodes>[];
      v.forEach((v) {
        arr0.add(VerifyQrCodeResqonseQrCodes.fromJson(v));
      });
      qrCodes = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['responseCode'] = responseCode;
    data['responseDesc'] = responseDesc;
    data['serverTimestamp'] = serverTimestamp;
    data['isReCheckFlag'] = isReCheckFlag;
    data['serialNo'] = serialNo;
    if (qrCodes != null) {
      final v = qrCodes;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['qrCodes'] = arr0;
    }
    return data;
  }
}
