///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VerifyPinResqonse {
/*
{
  "responseCode": "0",
  "responseDesc": "Process service request successfully.",
  "serverTimestamp": 1742442541344,
  "isReCheckFlag": "0",
  "isCorrect": "true",
  "isFinish": "true",
  "nextVerifyType": ""
} 
*/

  String? responseCode;
  String? responseDesc;
  int? serverTimestamp;
  String? isReCheckFlag;
  String? isCorrect;
  String? isFinish;
  String? nextVerifyType;

  VerifyPinResqonse({
    this.responseCode,
    this.responseDesc,
    this.serverTimestamp,
    this.isReCheckFlag,
    this.isCorrect,
    this.isFinish,
    this.nextVerifyType,
  });
  VerifyPinResqonse.fromJson(Map<String, dynamic> json) {
    responseCode = json['responseCode']?.toString();
    responseDesc = json['responseDesc']?.toString();
    serverTimestamp = json['serverTimestamp']?.toInt();
    isReCheckFlag = json['isReCheckFlag']?.toString();
    isCorrect = json['isCorrect']?.toString();
    isFinish = json['isFinish']?.toString();
    nextVerifyType = json['nextVerifyType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['responseCode'] = responseCode;
    data['responseDesc'] = responseDesc;
    data['serverTimestamp'] = serverTimestamp;
    data['isReCheckFlag'] = isReCheckFlag;
    data['isCorrect'] = isCorrect;
    data['isFinish'] = isFinish;
    data['nextVerifyType'] = nextVerifyType;
    return data;
  }
}
