///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetRechargeTransferListData {
/*
{
  "id": 1,
  "bank_name": "WavePay",
  "in_card_num": "56789",
  "in_card_name": "test1",
  "money": "2300.00"
} 
*/

  int? id;
  String? bankName;
  String? inCardNum;
  String? inCardName;
  String? money;

  GetRechargeTransferListData({
    this.id,
    this.bankName,
    this.inCardNum,
    this.inCardName,
    this.money,
  });
  GetRechargeTransferListData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    bankName = json['bank_name']?.toString();
    inCardNum = json['in_card_num']?.toString();
    inCardName = json['in_card_name']?.toString();
    money = json['money']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['bank_name'] = bankName;
    data['in_card_num'] = inCardNum;
    data['in_card_name'] = inCardName;
    data['money'] = money;
    return data;
  }
}

class GetRechargeTransferList {
/*
{
  "success": true,
  "data": {
    "id": 1,
    "bank_name": "WavePay",
    "in_card_num": "56789",
    "in_card_name": "test1",
    "money": "2300.00"
  },
  "error": ""
} 
*/

  bool? success;
  GetRechargeTransferListData? data;
  String? error;

  GetRechargeTransferList({
    this.success,
    this.data,
    this.error,
  });
  GetRechargeTransferList.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? GetRechargeTransferListData.fromJson(json['data'])
        : null;
    error = json['error']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['data'] = this.data!.toJson();
    data['error'] = error;
    return data;
  }
}
