///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SendMoneyResponseResponseMap {
/*
{
  "fees": 0.1,
  "commission": 0.1,
  "transactionId": "1209090009"
} 
*/

  double? fees;
  double? commission;
  String? transactionId;

  SendMoneyResponseResponseMap({
    this.fees,
    this.commission,
    this.transactionId,
  });
  SendMoneyResponseResponseMap.fromJson(Map<String, dynamic> json) {
    fees = json['fees']?.toDouble();
    commission = json['commission']?.toDouble();
    transactionId = json['transactionId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fees'] = fees;
    data['commission'] = commission;
    data['transactionId'] = transactionId;
    return data;
  }
}

class SendMoneyResponse {
/*
{
  "responseMap": {
    "fees": 0.1,
    "commission": 0.1,
    "transactionId": "1209090009"
  },
  "respTime": "Jun 18, 2024 08:46:20 AM",
  "message": "Please wait for the SMS confirmation to see the result",
  "statusCode": "SC0000"
} 
*/

  SendMoneyResponseResponseMap? responseMap;
  String? respTime;
  String? message;
  String? statusCode;

  SendMoneyResponse({
    this.responseMap,
    this.respTime,
    this.message,
    this.statusCode,
  });
  SendMoneyResponse.fromJson(Map<String, dynamic> json) {
    responseMap = (json['responseMap'] != null)
        ? SendMoneyResponseResponseMap.fromJson(json['responseMap'])
        : null;
    respTime = json['respTime']?.toString();
    message = json['message']?.toString();
    statusCode = json['statusCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (responseMap != null) {
      data['responseMap'] = responseMap!.toJson();
    }
    data['respTime'] = respTime;
    data['message'] = message;
    data['statusCode'] = statusCode;
    return data;
  }

  isSuccess() {
    return statusCode == 'SC0000';
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SendMoneyFailResponse {
/*
{
  "codeStatus": "PL001",
  "message": "Not enough balance.",
  "timestamp": "18-06-2024 09:29:41"
} 
*/

  String? codeStatus;
  String? message;
  String? timestamp;

  SendMoneyFailResponse({
    this.codeStatus,
    this.message,
    this.timestamp,
  });
  SendMoneyFailResponse.fromJson(Map<String, dynamic> json) {
    codeStatus = json['codeStatus']?.toString();
    message = json['message']?.toString();
    timestamp = json['timestamp']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['codeStatus'] = codeStatus;
    data['message'] = message;
    data['timestamp'] = timestamp;
    return data;
  }
}
