///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetBlacklistFlagData {
/*
{
  "blacklistFlag": "0",
  "status": "success"
} 
*/

  String? blacklistFlag;
  String? status;

  GetBlacklistFlagData({
    this.blacklistFlag,
    this.status,
  });
  GetBlacklistFlagData.fromJson(Map<String, dynamic> json) {
    blacklistFlag = json['blacklistFlag']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['blacklistFlag'] = blacklistFlag;
    data['status'] = status;
    return data;
  }
}

class GetBlacklistFlag {
/*
{
  "clientRefID": "20240905121617361192",
  "serviceRefID": "CFS20240905111617890997",
  "status": "S",
  "timestamp": "2024-09-05T11:16:17.905+07:00",
  "data": {
    "blacklistFlag": "0",
    "status": "success"
  }
} 
*/

  String? clientRefID;
  String? serviceRefID;
  String? status;
  String? timestamp;
  GetBlacklistFlagData? data;

  GetBlacklistFlag({
    this.clientRefID,
    this.serviceRefID,
    this.status,
    this.timestamp,
    this.data,
  });
  GetBlacklistFlag.fromJson(Map<String, dynamic> json) {
    clientRefID = json['clientRefID']?.toString();
    serviceRefID = json['serviceRefID']?.toString();
    status = json['status']?.toString();
    timestamp = json['timestamp']?.toString();
    data = (json['data'] != null)
        ? GetBlacklistFlagData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['clientRefID'] = clientRefID;
    data['serviceRefID'] = serviceRefID;
    data['status'] = status;
    data['timestamp'] = timestamp;
    data['data'] = this.data!.toJson();
    return data;
  }
}
