///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAccountSummaryListResponseDataAccountSummaryList {
/*
{
  "rowCount": 0,
  "accountId": "20240804949212",
  "accountNo": "1901675135",
  "accountNoNotFormat": "5a7d34f00c51210b793bbc70fab1f333",
  "accountNoMasking": "xxx-x-x7513-x",
  "accountName": "MS. SUMINTA PANSANGA",
  "accountNameTh": "MS. SUMINTA PANSANGA",
  "accountType": "SA",
  "accountTypeKey": "label.account.type.sa",
  "accountDisplayName": "MS. SUMINTA PANSANGA",
  "nicknameType": "OWNAC",
  "availableBalance": "2.80",
  "acctBalance": "2.80",
  "clearingAmt": "0.00",
  "holdAmt": "0.00",
  "accountLabelStatus": "ACTIVE",
  "responseInfoTime": "2024-09-04T16:36:11.072+07:00"
} 
*/

  int? rowCount;
  String? accountId;
  String? accountNo;
  String? accountNoNotFormat;
  String? accountNoMasking;
  String? accountName;
  String? accountNameTh;
  String? accountType;
  String? accountTypeKey;
  String? accountDisplayName;
  String? nicknameType;
  String? availableBalance;
  String? acctBalance;
  String? clearingAmt;
  String? holdAmt;
  String? accountLabelStatus;
  String? responseInfoTime;

  GetAccountSummaryListResponseDataAccountSummaryList({
    this.rowCount,
    this.accountId,
    this.accountNo,
    this.accountNoNotFormat,
    this.accountNoMasking,
    this.accountName,
    this.accountNameTh,
    this.accountType,
    this.accountTypeKey,
    this.accountDisplayName,
    this.nicknameType,
    this.availableBalance,
    this.acctBalance,
    this.clearingAmt,
    this.holdAmt,
    this.accountLabelStatus,
    this.responseInfoTime,
  });
  GetAccountSummaryListResponseDataAccountSummaryList.fromJson(
      Map<String, dynamic> json) {
    rowCount = json['rowCount']?.toInt();
    accountId = json['accountId']?.toString();
    accountNo = json['accountNo']?.toString();
    accountNoNotFormat = json['accountNoNotFormat']?.toString();
    accountNoMasking = json['accountNoMasking']?.toString();
    accountName = json['accountName']?.toString();
    accountNameTh = json['accountNameTh']?.toString();
    accountType = json['accountType']?.toString();
    accountTypeKey = json['accountTypeKey']?.toString();
    accountDisplayName = json['accountDisplayName']?.toString();
    nicknameType = json['nicknameType']?.toString();
    availableBalance = json['availableBalance']?.toString();
    acctBalance = json['acctBalance']?.toString();
    clearingAmt = json['clearingAmt']?.toString();
    holdAmt = json['holdAmt']?.toString();
    accountLabelStatus = json['accountLabelStatus']?.toString();
    responseInfoTime = json['responseInfoTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rowCount'] = rowCount;
    data['accountId'] = accountId;
    data['accountNo'] = accountNo;
    data['accountNoNotFormat'] = accountNoNotFormat;
    data['accountNoMasking'] = accountNoMasking;
    data['accountName'] = accountName;
    data['accountNameTh'] = accountNameTh;
    data['accountType'] = accountType;
    data['accountTypeKey'] = accountTypeKey;
    data['accountDisplayName'] = accountDisplayName;
    data['nicknameType'] = nicknameType;
    data['availableBalance'] = availableBalance;
    data['acctBalance'] = acctBalance;
    data['clearingAmt'] = clearingAmt;
    data['holdAmt'] = holdAmt;
    data['accountLabelStatus'] = accountLabelStatus;
    data['responseInfoTime'] = responseInfoTime;
    return data;
  }
}

class GetAccountSummaryListResponseData {
/*
{
  "rowCount": 0,
  "accountSummaryList": [
    {
      "rowCount": 0,
      "accountId": "20240804949212",
      "accountNo": "1901675135",
      "accountNoNotFormat": "5a7d34f00c51210b793bbc70fab1f333",
      "accountNoMasking": "xxx-x-x7513-x",
      "accountName": "MS. SUMINTA PANSANGA",
      "accountNameTh": "MS. SUMINTA PANSANGA",
      "accountType": "SA",
      "accountTypeKey": "label.account.type.sa",
      "accountDisplayName": "MS. SUMINTA PANSANGA",
      "nicknameType": "OWNAC",
      "availableBalance": "2.80",
      "acctBalance": "2.80",
      "clearingAmt": "0.00",
      "holdAmt": "0.00",
      "accountLabelStatus": "ACTIVE",
      "responseInfoTime": "2024-09-04T16:36:11.072+07:00"
    }
  ],
  "totalList": 1,
  "availableBalanceSum": "2.80",
  "lastestInfoTime": "2024-09-04T16:36:11.072+07:00"
} 
*/

  int? rowCount;
  List<GetAccountSummaryListResponseDataAccountSummaryList?>?
      accountSummaryList;
  int? totalList;
  String? availableBalanceSum;
  String? lastestInfoTime;

  GetAccountSummaryListResponseData({
    this.rowCount,
    this.accountSummaryList,
    this.totalList,
    this.availableBalanceSum,
    this.lastestInfoTime,
  });
  GetAccountSummaryListResponseData.fromJson(Map<String, dynamic> json) {
    rowCount = json['rowCount']?.toInt();
    if (json['accountSummaryList'] != null) {
      final v = json['accountSummaryList'];
      final arr0 = <GetAccountSummaryListResponseDataAccountSummaryList>[];
      v.forEach((v) {
        arr0.add(
            GetAccountSummaryListResponseDataAccountSummaryList.fromJson(v));
      });
      accountSummaryList = arr0;
    }
    totalList = json['totalList']?.toInt();
    availableBalanceSum = json['availableBalanceSum']?.toString();
    lastestInfoTime = json['lastestInfoTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rowCount'] = rowCount;
    if (accountSummaryList != null) {
      final v = accountSummaryList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['accountSummaryList'] = arr0;
    }
    data['totalList'] = totalList;
    data['availableBalanceSum'] = availableBalanceSum;
    data['lastestInfoTime'] = lastestInfoTime;
    return data;
  }
}

class GetAccountSummaryListResponse {
/*
{
  "clientRefID": "20240904173610419950",
  "serviceRefID": "ACS20240904163610797743",
  "status": "S",
  "timestamp": "2024-09-04T16:36:11.131+07:00",
  "data": {
    "rowCount": 0,
    "accountSummaryList": [
      {
        "rowCount": 0,
        "accountId": "20240804949212",
        "accountNo": "1901675135",
        "accountNoNotFormat": "5a7d34f00c51210b793bbc70fab1f333",
        "accountNoMasking": "xxx-x-x7513-x",
        "accountName": "MS. SUMINTA PANSANGA",
        "accountNameTh": "MS. SUMINTA PANSANGA",
        "accountType": "SA",
        "accountTypeKey": "label.account.type.sa",
        "accountDisplayName": "MS. SUMINTA PANSANGA",
        "nicknameType": "OWNAC",
        "availableBalance": "2.80",
        "acctBalance": "2.80",
        "clearingAmt": "0.00",
        "holdAmt": "0.00",
        "accountLabelStatus": "ACTIVE",
        "responseInfoTime": "2024-09-04T16:36:11.072+07:00"
      }
    ],
    "totalList": 1,
    "availableBalanceSum": "2.80",
    "lastestInfoTime": "2024-09-04T16:36:11.072+07:00"
  }
} 
*/

  String? clientRefID;
  String? serviceRefID;
  String? status;
  String? timestamp;
  GetAccountSummaryListResponseData? data;

  GetAccountSummaryListResponse({
    this.clientRefID,
    this.serviceRefID,
    this.status,
    this.timestamp,
    this.data,
  });
  GetAccountSummaryListResponse.fromJson(Map<String, dynamic> json) {
    clientRefID = json['clientRefID']?.toString();
    serviceRefID = json['serviceRefID']?.toString();
    status = json['status']?.toString();
    timestamp = json['timestamp']?.toString();
    data = (json['data'] != null)
        ? GetAccountSummaryListResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['clientRefID'] = clientRefID;
    data['serviceRefID'] = serviceRefID;
    data['status'] = status;
    data['timestamp'] = timestamp;
    data['data'] = this.data!.toJson();
    return data;
  }
}
