///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TransactionDetailResponseData {
/*
{
  "rowCount": 0,
  "bankNameTh": "BAYA",
  "bankNameEn": "BAYA",
  "toAccountNo": "8034053058",
  "toAccountNoMarking": "xxx-x-x5305-x",
  "toAccountNameTh": "PHUTPUHUT P++",
  "toAccountNameEn": "PHUTPUHUT P++",
  "memo": ""
} 
*/

  int? rowCount;
  String? bankNameTh;
  String? bankNameEn;
  String? toAccountNo;
  String? toAccountNoMarking;
  String? toAccountNameTh;
  String? toAccountNameEn;
  String? memo;

  TransactionDetailResponseData({
    this.rowCount,
    this.bankNameTh,
    this.bankNameEn,
    this.toAccountNo,
    this.toAccountNoMarking,
    this.toAccountNameTh,
    this.toAccountNameEn,
    this.memo,
  });
  TransactionDetailResponseData.fromJson(Map<String, dynamic> json) {
    rowCount = json['rowCount']?.toInt();
    bankNameTh = json['bankNameTh']?.toString();
    bankNameEn = json['bankNameEn']?.toString();
    toAccountNo = json['toAccountNo']?.toString();
    toAccountNoMarking = json['toAccountNoMarking']?.toString();
    toAccountNameTh = json['toAccountNameTh']?.toString();
    toAccountNameEn = json['toAccountNameEn']?.toString();
    memo = json['memo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rowCount'] = rowCount;
    data['bankNameTh'] = bankNameTh;
    data['bankNameEn'] = bankNameEn;
    data['toAccountNo'] = toAccountNo;
    data['toAccountNoMarking'] = toAccountNoMarking;
    data['toAccountNameTh'] = toAccountNameTh;
    data['toAccountNameEn'] = toAccountNameEn;
    data['memo'] = memo;
    return data;
  }
}

class TransactionDetailResponse {
/*
{
  "clientRefID": "20240918165900172228",
  "serviceRefID": "ACS20240918155900872153",
  "status": "S",
  "timestamp": "2024-09-18T15:59:01.415+07:00",
  "data": {
    "rowCount": 0,
    "bankNameTh": "BAYA",
    "bankNameEn": "BAYA",
    "toAccountNo": "8034053058",
    "toAccountNoMarking": "xxx-x-x5305-x",
    "toAccountNameTh": "PHUTPUHUT P++",
    "toAccountNameEn": "PHUTPUHUT P++",
    "memo": ""
  }
} 
*/

  String? clientRefID;
  String? serviceRefID;
  String? status;
  String? timestamp;
  TransactionDetailResponseData? data;

  TransactionDetailResponse({
    this.clientRefID,
    this.serviceRefID,
    this.status,
    this.timestamp,
    this.data,
  });
  TransactionDetailResponse.fromJson(Map<String, dynamic> json) {
    clientRefID = json['clientRefID']?.toString();
    serviceRefID = json['serviceRefID']?.toString();
    status = json['status']?.toString();
    timestamp = json['timestamp']?.toString();
    data = (json['data'] != null)
        ? TransactionDetailResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['clientRefID'] = clientRefID;
    data['serviceRefID'] = serviceRefID;
    data['status'] = status;
    data['timestamp'] = timestamp;
    data['data'] = this.data!.toJson();
    return data;
  }
}
