///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ValidateSessionResponseDataUserProfilesRoleList {
/*
{
  "roleId": "2",
  "roleName": "Admin"
} 
*/

  String? roleId;
  String? roleName;

  ValidateSessionResponseDataUserProfilesRoleList({
    this.roleId,
    this.roleName,
  });
  ValidateSessionResponseDataUserProfilesRoleList.fromJson(
      Map<String, dynamic> json) {
    roleId = json['roleId']?.toString();
    roleName = json['roleName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['roleId'] = roleId;
    data['roleName'] = roleName;
    return data;
  }
}

class ValidateSessionResponseDataUserProfiles {
/*
{
  "ibId": "d27c6f06fc165f4875dfc04828092b71",
  "ibIdGA": "6b161a30ab74807cbb7d7c1a181efb0c",
  "adsIbId": "bjbdjhjdiafieh",
  "roleList": [
    {
      "roleId": "2",
      "roleName": "Admin"
    }
  ],
  "companyId": "4cc1a079ff8acbcd1afd0cdfdc772af9",
  "companyNameTH": "สุมินตา",
  "companyNameEN": "SUMINTA",
  "lastNameCompanyTH": "ปั้นสง่า",
  "lastNameCompanyEN": "PANSANGA",
  "firstNameTH": "สุมินตา",
  "lastNameTH": "ปั้นสง่า",
  "firstNameEN": "SUMINTA",
  "lastNameEN": "PANSANGA",
  "custType": "IX",
  "img": null,
  "blacklist": "0",
  "titleId": "3",
  "showRoleFlag": "N"
} 
*/

  String? ibId;
  String? ibIdGA;
  String? adsIbId;
  List<ValidateSessionResponseDataUserProfilesRoleList?>? roleList;
  String? companyId;
  String? companyNameTH;
  String? companyNameEN;
  String? lastNameCompanyTH;
  String? lastNameCompanyEN;
  String? firstNameTH;
  String? lastNameTH;
  String? firstNameEN;
  String? lastNameEN;
  String? custType;
  String? img;
  String? blacklist;
  String? titleId;
  String? showRoleFlag;

  ValidateSessionResponseDataUserProfiles({
    this.ibId,
    this.ibIdGA,
    this.adsIbId,
    this.roleList,
    this.companyId,
    this.companyNameTH,
    this.companyNameEN,
    this.lastNameCompanyTH,
    this.lastNameCompanyEN,
    this.firstNameTH,
    this.lastNameTH,
    this.firstNameEN,
    this.lastNameEN,
    this.custType,
    this.img,
    this.blacklist,
    this.titleId,
    this.showRoleFlag,
  });
  ValidateSessionResponseDataUserProfiles.fromJson(Map<String, dynamic> json) {
    ibId = json['ibId']?.toString();
    ibIdGA = json['ibIdGA']?.toString();
    adsIbId = json['adsIbId']?.toString();
    if (json['roleList'] != null) {
      final v = json['roleList'];
      final arr0 = <ValidateSessionResponseDataUserProfilesRoleList>[];
      v.forEach((v) {
        arr0.add(ValidateSessionResponseDataUserProfilesRoleList.fromJson(v));
      });
      roleList = arr0;
    }
    companyId = json['companyId']?.toString();
    companyNameTH = json['companyNameTH']?.toString();
    companyNameEN = json['companyNameEN']?.toString();
    lastNameCompanyTH = json['lastNameCompanyTH']?.toString();
    lastNameCompanyEN = json['lastNameCompanyEN']?.toString();
    firstNameTH = json['firstNameTH']?.toString();
    lastNameTH = json['lastNameTH']?.toString();
    firstNameEN = json['firstNameEN']?.toString();
    lastNameEN = json['lastNameEN']?.toString();
    custType = json['custType']?.toString();
    img = json['img']?.toString();
    blacklist = json['blacklist']?.toString();
    titleId = json['titleId']?.toString();
    showRoleFlag = json['showRoleFlag']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ibId'] = ibId;
    data['ibIdGA'] = ibIdGA;
    data['adsIbId'] = adsIbId;
    if (roleList != null) {
      final v = roleList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['roleList'] = arr0;
    }
    data['companyId'] = companyId;
    data['companyNameTH'] = companyNameTH;
    data['companyNameEN'] = companyNameEN;
    data['lastNameCompanyTH'] = lastNameCompanyTH;
    data['lastNameCompanyEN'] = lastNameCompanyEN;
    data['firstNameTH'] = firstNameTH;
    data['lastNameTH'] = lastNameTH;
    data['firstNameEN'] = firstNameEN;
    data['lastNameEN'] = lastNameEN;
    data['custType'] = custType;
    data['img'] = img;
    data['blacklist'] = blacklist;
    data['titleId'] = titleId;
    data['showRoleFlag'] = showRoleFlag;
    return data;
  }
}

class ValidateSessionResponseData {
/*
{
  "rowCount": 0,
  "language": "EN",
  "username": "Suminta41",
  "userProfiles": [
    {
      "ibId": "d27c6f06fc165f4875dfc04828092b71",
      "ibIdGA": "6b161a30ab74807cbb7d7c1a181efb0c",
      "adsIbId": "bjbdjhjdiafieh",
      "roleList": [
        {
          "roleId": "2",
          "roleName": "Admin"
        }
      ],
      "companyId": "4cc1a079ff8acbcd1afd0cdfdc772af9",
      "companyNameTH": "สุมินตา",
      "companyNameEN": "SUMINTA",
      "lastNameCompanyTH": "ปั้นสง่า",
      "lastNameCompanyEN": "PANSANGA",
      "firstNameTH": "สุมินตา",
      "lastNameTH": "ปั้นสง่า",
      "firstNameEN": "SUMINTA",
      "lastNameEN": "PANSANGA",
      "custType": "IX",
      "img": null,
      "blacklist": "0",
      "titleId": "3",
      "showRoleFlag": "N"
    }
  ],
  "secType": "7",
  "secTypeFlag": "",
  "googleTagManagerId": "GTM-KP7ZJLZ",
  "recaptchaSiteKey": "6Lecz88aAAAAADMoaLKBfDC7s9faxdiaYWiCYL8w",
  "lastLoginDatetime": "2024-09-04 09:47:22.000",
  "showKXMP": "",
  "showKS": "",
  "showKA": ""
} 
*/

  int? rowCount;
  String? language;
  String? username;
  List<ValidateSessionResponseDataUserProfiles?>? userProfiles;
  String? secType;
  String? secTypeFlag;
  String? googleTagManagerId;
  String? recaptchaSiteKey;
  String? lastLoginDatetime;
  String? showKXMP;
  String? showKS;
  String? showKA;

  ValidateSessionResponseData({
    this.rowCount,
    this.language,
    this.username,
    this.userProfiles,
    this.secType,
    this.secTypeFlag,
    this.googleTagManagerId,
    this.recaptchaSiteKey,
    this.lastLoginDatetime,
    this.showKXMP,
    this.showKS,
    this.showKA,
  });
  ValidateSessionResponseData.fromJson(Map<String, dynamic> json) {
    rowCount = json['rowCount']?.toInt();
    language = json['language']?.toString();
    username = json['username']?.toString();
    if (json['userProfiles'] != null) {
      final v = json['userProfiles'];
      final arr0 = <ValidateSessionResponseDataUserProfiles>[];
      v.forEach((v) {
        arr0.add(ValidateSessionResponseDataUserProfiles.fromJson(v));
      });
      userProfiles = arr0;
    }
    secType = json['secType']?.toString();
    secTypeFlag = json['secTypeFlag']?.toString();
    googleTagManagerId = json['googleTagManagerId']?.toString();
    recaptchaSiteKey = json['recaptchaSiteKey']?.toString();
    lastLoginDatetime = json['lastLoginDatetime']?.toString();
    showKXMP = json['showKXMP']?.toString();
    showKS = json['showKS']?.toString();
    showKA = json['showKA']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rowCount'] = rowCount;
    data['language'] = language;
    data['username'] = username;
    if (userProfiles != null) {
      final v = userProfiles;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['userProfiles'] = arr0;
    }
    data['secType'] = secType;
    data['secTypeFlag'] = secTypeFlag;
    data['googleTagManagerId'] = googleTagManagerId;
    data['recaptchaSiteKey'] = recaptchaSiteKey;
    data['lastLoginDatetime'] = lastLoginDatetime;
    data['showKXMP'] = showKXMP;
    data['showKS'] = showKS;
    data['showKA'] = showKA;
    return data;
  }
}

class ValidateSessionResponse {
/*
{
  "clientRefID": "20240904104842866505",
  "serviceRefID": "ATC20240904094843128910",
  "status": "S",
  "timestamp": "2024-09-04T09:48:43.716+07:00",
  "data": {
    "rowCount": 0,
    "language": "EN",
    "username": "Suminta41",
    "userProfiles": [
      {
        "ibId": "d27c6f06fc165f4875dfc04828092b71",
        "ibIdGA": "6b161a30ab74807cbb7d7c1a181efb0c",
        "adsIbId": "bjbdjhjdiafieh",
        "roleList": [
          {
            "roleId": "2",
            "roleName": "Admin"
          }
        ],
        "companyId": "4cc1a079ff8acbcd1afd0cdfdc772af9",
        "companyNameTH": "สุมินตา",
        "companyNameEN": "SUMINTA",
        "lastNameCompanyTH": "ปั้นสง่า",
        "lastNameCompanyEN": "PANSANGA",
        "firstNameTH": "สุมินตา",
        "lastNameTH": "ปั้นสง่า",
        "firstNameEN": "SUMINTA",
        "lastNameEN": "PANSANGA",
        "custType": "IX",
        "img": null,
        "blacklist": "0",
        "titleId": "3",
        "showRoleFlag": "N"
      }
    ],
    "secType": "7",
    "secTypeFlag": "",
    "googleTagManagerId": "GTM-KP7ZJLZ",
    "recaptchaSiteKey": "6Lecz88aAAAAADMoaLKBfDC7s9faxdiaYWiCYL8w",
    "lastLoginDatetime": "2024-09-04 09:47:22.000",
    "showKXMP": "",
    "showKS": "",
    "showKA": ""
  }
} 
*/

  String? clientRefID;
  String? serviceRefID;
  String? status;
  String? timestamp;
  ValidateSessionResponseData? data;

  ValidateSessionResponse({
    this.clientRefID,
    this.serviceRefID,
    this.status,
    this.timestamp,
    this.data,
  });
  ValidateSessionResponse.fromJson(Map<String, dynamic> json) {
    clientRefID = json['clientRefID']?.toString();
    serviceRefID = json['serviceRefID']?.toString();
    status = json['status']?.toString();
    timestamp = json['timestamp']?.toString();
    data = (json['data'] != null)
        ? ValidateSessionResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['clientRefID'] = clientRefID;
    data['serviceRefID'] = serviceRefID;
    data['status'] = status;
    data['timestamp'] = timestamp;
    data['data'] = this.data!.toJson();
    return data;
  }
}
