///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
final class HistoriesResponseResponseMapTnxHistoryList implements Comparable {
/*
{
  "transDate": "2024-06-11 16:33:38.610",
  "transId": "1121452017",
  "transType": "sendmoney",
  "transSubType": "TOMA",
  "title": "Receive Money",
  "iconUrl": "",
  "msisdn": "9455990193",
  "status": "2",
  "amount": 2004,
  "action": "[{\"label\":\"from\",\"lableType\":\"text\",\"value\":\"(****6203)\",\"valueType\":\"text\",\"orderId\":1}]",
  "product": "SEND_MONEY",
  "fee": 0,
  "bonus": 0,
  "bankCode": "",
  "perspective": "RECEIVER",
  "cashierId": null,
  "cashierName": null
} 
*/

  String? transDate;
  String? transId;
  String? transType;
  String? transSubType;
  String? title;
  String? iconUrl;
  String? msisdn;
  String? status;
  int? amount;
  String? action;
  String? product;
  int? fee;
  int? bonus;
  String? bankCode;
  String? perspective;
  String? cashierId;
  String? cashierName;

  DateTime? _transDateTime;

  HistoriesResponseResponseMapTnxHistoryList({
    this.transDate,
    this.transId,
    this.transType,
    this.transSubType,
    this.title,
    this.iconUrl,
    this.msisdn,
    this.status,
    this.amount,
    this.action,
    this.product,
    this.fee,
    this.bonus,
    this.bankCode,
    this.perspective,
    this.cashierId,
    this.cashierName,
  });
  HistoriesResponseResponseMapTnxHistoryList.fromJson(
      Map<String, dynamic> json) {
    transDate = json['transDate']?.toString();
    transId = json['transId']?.toString();
    transType = json['transType']?.toString();
    transSubType = json['transSubType']?.toString();
    title = json['title']?.toString();
    iconUrl = json['iconUrl']?.toString();
    msisdn = json['msisdn']?.toString();
    status = json['status']?.toString();
    amount = json['amount']?.toInt();
    action = json['action']?.toString();
    product = json['product']?.toString();
    fee = json['fee']?.toInt();
    bonus = json['bonus']?.toInt();
    bankCode = json['bankCode']?.toString();
    perspective = json['perspective']?.toString();
    cashierId = json['cashierId']?.toString();
    cashierName = json['cashierName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['transDate'] = transDate;
    data['transId'] = transId;
    data['transType'] = transType;
    data['transSubType'] = transSubType;
    data['title'] = title;
    data['iconUrl'] = iconUrl;
    data['msisdn'] = msisdn;
    data['status'] = status;
    data['amount'] = amount;
    data['action'] = action;
    data['product'] = product;
    data['fee'] = fee;
    data['bonus'] = bonus;
    data['bankCode'] = bankCode;
    data['perspective'] = perspective;
    data['cashierId'] = cashierId;
    data['cashierName'] = cashierName;
    return data;
  }

  bool isReceve() {
    return perspective == 'RECEIVER' &&
        (title == 'Receive Money' || title == 'Cash In');
  }

  DateTime get transDateTime {
    _transDateTime ??= toDateTime();
    return _transDateTime!;
  }

  DateTime toDateTime() {
    return DateTime.parse(transDate ?? '');
  }

  @override
  int compareTo(other) {
    if (other is HistoriesResponseResponseMapTnxHistoryList) {
      final time1 = transDateTime.microsecondsSinceEpoch;
      final time2 = other.transDateTime.microsecondsSinceEpoch;
      if (time1 == time2) return 0;
      return time1 - time2;
    }
    return 0;
  }
}

class HistoriesResponseResponseMap {
/*
{
  "statusCode": null,
  "respTime": null,
  "tnxHistoryList": [
    {
      "transDate": "2024-06-11 16:33:38.610",
      "transId": "1121452017",
      "transType": "sendmoney",
      "transSubType": "TOMA",
      "title": "Receive Money",
      "iconUrl": "",
      "msisdn": "9455990193",
      "status": "2",
      "amount": 2004,
      "action": "[{\"label\":\"from\",\"lableType\":\"text\",\"value\":\"(****6203)\",\"valueType\":\"text\",\"orderId\":1}]",
      "product": "SEND_MONEY",
      "fee": 0,
      "bonus": 0,
      "bankCode": "",
      "perspective": "RECEIVER",
      "cashierId": null,
      "cashierName": null
    }
  ],
  "totalCount": 9
} 
*/

  String? statusCode;
  String? respTime;
  List<HistoriesResponseResponseMapTnxHistoryList?>? tnxHistoryList;
  int? totalCount;

  HistoriesResponseResponseMap({
    this.statusCode,
    this.respTime,
    this.tnxHistoryList,
    this.totalCount,
  });
  HistoriesResponseResponseMap.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toString();
    respTime = json['respTime']?.toString();
    if (json['tnxHistoryList'] != null) {
      final v = json['tnxHistoryList'];
      final arr0 = <HistoriesResponseResponseMapTnxHistoryList>[];
      v.forEach((v) {
        arr0.add(HistoriesResponseResponseMapTnxHistoryList.fromJson(v));
      });
      tnxHistoryList = arr0;
    }
    totalCount = json['totalCount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['respTime'] = respTime;
    if (tnxHistoryList != null) {
      // final v = tnxHistoryList;
      // final arr0 = [];
      // v!.forEach((v) {
      //   arr0.add(v!.toJson());
      // });
      // data['tnxHistoryList'] = arr0;
      data['tnxHistoryList'] = tnxHistoryList!.map((v) => v!.toJson()).toList();
    }
    data['totalCount'] = totalCount;
    return data;
  }
}

class HistoriesResponse {
/*
{
  "responseMap": {
    "statusCode": null,
    "respTime": null,
    "tnxHistoryList": [
      {
        "transDate": "2024-06-11 16:33:38.610",
        "transId": "1121452017",
        "transType": "sendmoney",
        "transSubType": "TOMA",
        "title": "Receive Money",
        "iconUrl": "",
        "msisdn": "9455990193",
        "status": "2",
        "amount": 2004,
        "action": "[{\"label\":\"from\",\"lableType\":\"text\",\"value\":\"(****6203)\",\"valueType\":\"text\",\"orderId\":1}]",
        "product": "SEND_MONEY",
        "fee": 0,
        "bonus": 0,
        "bankCode": "",
        "perspective": "RECEIVER",
        "cashierId": null,
        "cashierName": null
      }
    ],
    "totalCount": 9
  },
  "message": "Transaction History Successfully Retrieved.",
  "statusCode": null,
  "status": 0,
  "respTime": null
} 
*/

  HistoriesResponseResponseMap? responseMap;
  String? message;
  String? statusCode;
  int? status;
  String? respTime;

  HistoriesResponse({
    this.responseMap,
    this.message,
    this.statusCode,
    this.status,
    this.respTime,
  });
  HistoriesResponse.fromJson(Map<String, dynamic> json) {
    responseMap = (json['responseMap'] != null)
        ? HistoriesResponseResponseMap.fromJson(json['responseMap'])
        : null;
    message = json['message']?.toString();
    statusCode = json['statusCode']?.toString();
    status = json['status']?.toInt();
    respTime = json['respTime']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (responseMap != null) {
      data['responseMap'] = responseMap!.toJson();
    }
    data['message'] = message;
    data['statusCode'] = statusCode;
    data['status'] = status;
    data['respTime'] = respTime;
    return data;
  }
}
