///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WalletBalanceResponseResponseMap {
/*
{
  "balance": 21100
} 
*/

  double? balance;

  WalletBalanceResponseResponseMap({
    this.balance,
  });
  WalletBalanceResponseResponseMap.fromJson(Map<String, dynamic> json) {
    balance = json['balance']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['balance'] = balance;
    return data;
  }
}

class WalletBalanceResponse {
/*
{
  "responseMap": {
    "balance": 21100
  },
  "message": "Balance is retrieved"
} 
*/

  WalletBalanceResponseResponseMap? responseMap;
  String? message;

  WalletBalanceResponse({
    this.responseMap,
    this.message,
  });
  WalletBalanceResponse.fromJson(Map<String, dynamic> json) {
    responseMap = (json['responseMap'] != null)
        ? WalletBalanceResponseResponseMap.fromJson(json['responseMap'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (responseMap != null) {
      data['responseMap'] = responseMap!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
