name: KBZ Release

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在匹配标签推送时触发

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'  # 确保使用正确的 Java 版本

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        # flutter-version: 'stable'  # 或者你需要的具体版本
        channel: master

    - name: Install dependencies
      run: flutter pub get

    - name: Setup bank type
      run: sed -i "" "s/static BankType bankType = BankType.*;/static BankType bankType = BankType.kbz;/g" lib/config/global_config.dart

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Rename APK
      run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/kbz_reporter.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/app/outputs/flutter-apk/kbz_reporter.apk

    - name: Echo token
      run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Flutter应用程序的新版本发布了！
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/kbz_reporter.apk
        asset_name: kbz_reporter.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}