name: auto report Release

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在匹配标签推送时触发

jobs:
  build-and-publish:
    runs-on: macos-latest
    strategy:
      matrix:
        bank: [kbz, wave, kbiz, aya]
        include:
          - bank: kbz
            app_name: "kbz report"
            logo: "ic_kbz_logo.png"
          - bank: wave
            app_name: "wave report"
            logo: "ic_wave_logo.png"
          - bank: kbiz
            app_name: "kbiz report"
            logo: "ic_bank_logo.png"
          - bank: aya
            app_name: "aya report"
            logo: "ic_bank_logo.png"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  # 确保使用正确的 Java 版本

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'  # 使用稳定版本
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Clean and rebuild
      run: |
        flutter clean
        flutter pub get

    - name: Create key.properties
      run: |
        cat << EOF > android/key.properties
        storePassword=${{ secrets.STOREPASSWORD }}
        keyPassword=${{ secrets.KEYPASSWORD }}
        keyAlias=${{ secrets.KEYALIAS }}
        storeFile=${{ secrets.STOREFILE }}
        EOF

    - name: Setup bank configuration
      run: |
        sed -i "" "s/static BankType bankType = BankType.*;/static BankType bankType = BankType.${{ matrix.bank }};/g" lib/config/global_config.dart
        sed -i '' 's|assets/ic_.*logo.png|assets/${{ matrix.logo }}|g' pubspec.yaml
        sed -i '' 's|applicationId = "com.example.auto_report.*"|applicationId = "com.example.auto_report.${{ matrix.bank }}"|g' android/app/build.gradle
        sed -i '' 's|android:label=".*report.*"|android:label="${{ matrix.app_name }}"|g' android/app/src/main/AndroidManifest.xml
    
    - name: Setup Icons
      run: |
        flutter pub get
        dart run icons_launcher:create

    - name: Run tests
      run: flutter test

    - name: Extract tag version
      id: extract_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build APK
      run: flutter build apk --release --android-skip-build-dependency-validation

    - name: Rename APK
      run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${{ matrix.bank }}_reporter_${{ env.version }}.apk

    - uses: actions/upload-artifact@v4
      with:
        name: apk-${{ matrix.bank }}
        path: build/app/outputs/flutter-apk/${{ matrix.bank }}_reporter_${{ env.version }}.apk
        retention-days: 1

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag version
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          pattern: apk-*
          path: ./downloads
          merge-multiple: true

      - name: List downloaded files
        run: ls -R ./downloads

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          name: ${{ env.version }}
          body: |
            auto report新版本发布了!
            
            包含以下版本：
            - KBZ Reporter
            - Wave Reporter
            - KBIZ Reporter
          draft: false
          prerelease: false
          files: |
            ./downloads/**/*.apk
