///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReportGeneralResponse {
/*
{
  "status": "T",
  "message": "wait"
} 
*/

  String? status;
  String? message;

  ReportGeneralResponse({
    this.status,
    this.message,
  });
  ReportGeneralResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    return data;
  }
}
